### ISSUE TITLE
Most converted models fail ONNX optimization

### ISSUE THREAD

**Issue by siorpaes** [jackwish/tflite2onnx#19] opened 2020-10-22 08:17 UTC
**Describe the bug**
ONNX models resulting from tflite conversion fail ONNX optimization process. ONNX checker does not report any problem, though.

**To Reproduce**
1. Download posenet_mobilenet_float_075_1_default_1.tflite model from here: [posenet_mobilenet_float](https://tfhub.dev/tensorflow/lite-model/posenet/mobilenet/float/075/1/default/1)
2. Convert it: `tflite2onnx  posenet_mobilenet_float_075_1_default_1.tflite test.onnx`
3. Optimize resulting model with attached script [optimize_model.py.gz](https://github.com/jackwish/tflite2onnx/files/5474349/optimize_model.py.gz): `python optimize_model.py --input test.onnx`
4. Obscure error is reported by ONNX optimizer

```
Processing model: test.onnx
Traceback (most recent call last):
  File "optimize_model.py", line 26, in <module>
    optimized_model = optimizer.optimize(model, ['eliminate_deadend'])
  File "/home/daz/anaconda3/envs/atonn/lib/python3.7/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at
```

**Comment by IkbeomJeon** [comment] 2020-10-22 08:58
Thank you, I'll confirm.

Now, I have been implementing conv_transpose, If the implementation is
complete, it will be committed to my forked repository with the test code.
(or Is there any code about that already in progress?)



2020년 10월 22일 (목) 오후 5:17, David <notifications@github.com>님이 작성:

**Comment by jackwish** [comment] 2020-10-31 01:45
@siorpaes Thank you for reporting this issue. And I am really sorry for missing this in my timeline. I will have a try today.

**Comment by jackwish** [comment] 2020-11-01 14:29
@siorpaes It seems that you forgot to attach the optimize script `optimize_model.py`.

And, I have tried to run the converted ONNX model with ONNXRuntime ([scripts attached](https://github.com/jackwish/tflite2onnx/files/5471049/test_models.py.tar.gz), changed from [our test script](https://github.com/jackwish/tflite2onnx/blob/master/tests/test_models.py#L82)), no issue found. I would like to take this as a compatibility issue of ONNX Optimizer, as the ONNX model we generated doesn't violate ONNX rules and ONNXRuntime can run it without problem.

@siorpaes Would you like to create an issue for ONNX Optimizer? We can try to discuss this with ONNX optimizer developers. Btw, I have a plan to look into the implementation of ONNX Optimizer, maybe we can take this issue as a chance.

**Comment by jackwish** [comment] 2020-11-01 14:31
Moved to `Ecosystem` as it looks like to be an ONNX Optimizer issue.

**Comment by siorpaes** [comment] 2020-11-02 10:48
Hello @jackwish whank you very much for coming back to me. I attached the missing script. Let me know if you need any further information.

**Comment by jackwish** [comment] 2020-11-03 02:36
Thank you @siorpaes for the update. I can reproduce the error with your script. As I have mentioned in https://github.com/jackwish/tflite2onnx/issues/19#issuecomment-720097208, would you like to [create an issue for ONNX Optimizer](https://github.com/onnx/onnx/issues/new/choose)? We can continue to discuss and see what we can do there.

**Comment by siorpaes** [comment] 2020-11-03 15:23
Thanks to you @jackwish. As you suggest, I will create an issue for ONNX optimizer. Would it be better to post the converted ONNX model directly or shall I illustrate the process on how to convert it from tflite with your tool ?

**Comment by jackwish** [comment] 2020-11-04 00:49
@siorpaes Thank you! Let's work with ONNX Optimizer guys to see what the next action can be.

**Comment by jackwish** [comment] 2020-11-11 10:32
Closing as it's actually an IR gap of ONNX tools. See
* [This issue reported to ONNX Optimizer](https://github.com/onnx/optimizer/issues/18)
* [The PR to fix IR gap](https://github.com/onnx/onnx/pull/3007)

**Closed by jackwish** 2020-11-11 10:32 UTC
Labels: Ecosystem
