### ISSUE TITLE
Unsupported data type: FP16, INT8 and etc.

### ISSUE THREAD

**Issue by dsJoe** [jackwish/tflite2onnx#30] opened 2020-11-19 07:33 UTC
I am trying to convert tflite to ONNX and getting an assertion error

![image](https://user-images.githubusercontent.com/28567999/99635075-7d78d100-2a67-11eb-8a17-1c2aff72bdc7.png)

Could you please help?

**Comment by erizmr** [comment] 2020-11-19 08:40
Hi @dsJoe ,
Thanks for coming here. It will be great if you can give more details about the tflite model for reproducing the issue ( or even better to attach the model here if it is convenient for you).

**Comment by jackwish** [comment] 2020-11-20 01:01
Thanks @erizmr for getting to this.

@dsJoe We have these `assert` here to check the logic that is not intended for currently, such that we can catch them as early as we can and check what needs to change in our code base. Would you please to attach the TFLite model to we can deep dive into it?

**Comment by dsJoe** [comment] 2020-11-20 11:24
Thank you for the reply

I couldn't attach the model since the size is more than 10 MB. I will send you the model over an email.

Meantime, attaching a smaller model where I am getting a different error message.
[lite-model_3.zip](https://github.com/jackwish/tflite2onnx/files/5573167/lite-model_3.zip)

The commands I used from Jupyter notebook to convert.

import tflite2onnx

tflite_path = './tf2litemodel/lite-model_3.tflite'
onnx_path = './onnxmodel'

tflite2onnx.convert(tflite_path, onnx_path) 


Providing the full error logs:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-10-8a71e70258f5> in <module>
      4 onnx_path = './onnxmodel'
      5 
----> 6 tflite2onnx.convert(tflite_path, onnx_path)

~\.conda\envs\py38\lib\site-packages\tflite2onnx\convert.py in convert(tflite_path, onnx_path, explicit_layouts)
     42 
     43     model = Model(im)
---> 44     model.convert(explicit_layouts)
     45     model.save(onnx_path)
     46     logger.info("Converted ONNX model: %s", onnx_path)

~\.conda\envs\py38\lib\site-packages\tflite2onnx\model.py in convert(self, explicit_layouts)
     37 
     38     def convert(self, explicit_layouts):
---> 39         self.parse()
     40         logger.debug("Converting...")
     41         for g in self.graphes:

~\.conda\envs\py38\lib\site-packages\tflite2onnx\model.py in parse(self)
     29 
     30         for g in self.graphes:
---> 31             g.parse()
     32 
     33         self.setParsed()

~\.conda\envs\py38\lib\site-packages\tflite2onnx\graph.py in parse(self)
     60         for i in range(self.graph.OperatorsLength()):
     61             logger.debug("Parsing operator: %d", i)
---> 62             op = self.OPCFactory.create(i)
     63             op.parse()
     64             self.ops.append(op)

~\.conda\envs\py38\lib\site-packages\tflite2onnx\op\common.py in create(self, index)
    149         opcode = self.model.OperatorCodes(op.OpcodeIndex()).BuiltinCode()
    150         if opcode not in OpFactory.registry:
--> 151             raise NotImplementedError("Unsupported TFLite OP: {}".format(opcode))
    152 
    153         op_converter = OpFactory.registry[opcode]

NotImplementedError: Unsupported TFLite OP: 23

Please let me know if I need to provide any other details.

**Comment by IkbeomJeon** [comment] 2020-11-20 13:51
I also faced same problem.
Now, my target tflite model includes 'float16' tensors. But it seems to be not supported now.

**Comment by IkbeomJeon** [comment] 2020-11-20 13:54
i attached model [https://www.dropbox.com/s/yzvgv6grdmvo9nv/object_detection_3d_sneakers.tflite?dl=0](url)

**Comment by jackwish** [comment] 2020-11-20 14:33
@dsJoe, I tried your model it's because the current quantization support `uint8` as data type only. I think we can extend it to `int8` in the next version. To workaround, maybe you try to generate a TFLite model with `uint8` data type. Btw, just curious, are you using dynamic quantization of TensorFlow Lite to generate the model?

@IkbeomJeon I got an assertion when processing the first operator `Dequantize`, it seems we may have some bugs in processing raw quantization operators. To be honest, the path was not seriously tested, I can deep dive later. It seems your model uses float operators but all weights are quantized. That is pretty interesting as we can just use quantized operators. Is this expected? I am very interested in why to use such models...

**Comment by dsJoe** [comment] 2020-11-23 06:07
@jackwish Thank you for your suggestion. Could you help me to generate a TFLite model with uint8 data type. I have never done it.

I am using dynamic quantization to generate the TFLite model.

**Comment by jackwish** [comment] 2020-11-23 12:14
@deiruch encountered a similar issue when converting [segm_full_v491.zip](https://github.com/jackwish/tflite2onnx/files/5581862/segm_full_v491.zip) which is the background segmentation from Google Meet in #31 

@deiruch we can move the discussions to here.

**Comment by jackwish** [comment] 2020-11-23 12:24
> @jackwish Thank you for your suggestion. Could you help me to generate a TFLite model with uint8 data type. I have never done it.
> 
> I am using dynamic quantization to generate the TFLite model.

@dsJoe (and to many ones who have similar issues) I think that depends on why you want to convert a quantized TFLite model (as ONNX's quantization support is trivial, it's pretty interesting for me) to ONNX. In general, I don't suggest converting a quantized TFLite model to ONNX except that TFLite model is generated with TensorFlow Quantization-aware Training which maintains sound prediction accuracy of the TFLite model. Rather, for cases like dynamic quantization, I'd suggest converting the original FP32 model to ONNX and then quantize the ONNX model by either [the ONNXRuntime tool](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/quantize.py) or [ONNX backends such as TensorRT](https://github.com/NVIDIA/TensorRT/issues/557).

**Comment by jackwish** [comment] 2020-11-23 12:41
@IkbeomJeon @dsJoe @erizmr @deiruch I have created issue #32 to get to understand your use case, would you mind provide some input if convenient? Thanks!

**Comment by jackwish** [comment] 2020-11-29 14:32
Hey guys, an update here: FP16 is not natively supported by TFLite - operators like `Add` and `Conv` don't support FP16. And it seems TensorFlow is converting FP16 to FP32 if we created a model with the FP16 data type. For example, we got a model description like below which is an `Add` operator that accepts two FP16 inputs. Two `Cast` layers are added to make the model run (not sure if it's a TF core issue or a Keras issue though). The model is rejected when we trying to convert it into TFLite as the TFLite converter doesn't support `Cast`.

```
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
        tf.Cast {Truncate = false, device = ""}
<unknown>:0: note: see current operation: "func"() ( {
^bb0(%arg0: tensor<1x2x3x4xf16>, %arg1: tensor<1x2x3x4xf16>):  // no predecessors
  %0 = "tf.Cast"(%arg0) {Truncate = false, device = ""} : (tensor<1x2x3x4xf16>) -> tensor<1x2x3x4xf32>
  %1 = "tf.Cast"(%arg1) {Truncate = false, device = ""} : (tensor<1x2x3x4xf16>) -> tensor<1x2x3x4xf32>
  %2 = "tfl.add"(%0, %1) {fused_activation_function = "NONE"} : (tensor<1x2x3x4xf32>, tensor<1x2x3x4xf32>) -> tensor<1x2x3x4xf32>
  "std.return"(%2) : (tensor<1x2x3x4xf32>) -> ()
}) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "A,B", outputs = "Identity"}, type = (tensor<1x2x3x4xf16>, tensor<1x2x3x4xf16>) -> t
ensor<1x2x3x4xf32>} : () -> ()
```

It seems to me FP16 exists only used in [FP16 quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#float16_quantization). As of today, I'd recommend to use [Full integer quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization) and quantization-aware training.

To workaround this FP16 issue, I have disabled the `assert` by logging a warning. There is no test for the FP16 path so far. The disabling works for INT8 too. **Please help to create some tiny models to protect the codebase if you really need to get FP16 or INT8 to work**. Thanks!

**Comment by kapulkin** [comment] 2020-12-26 19:01
I found, that tf.lite in Tensorflow 2.0 does not support uint8 in operations unfortunately.

It's written there: https://github.com/tensorflow/tensorflow/issues/38285#issuecomment-673334366 and there in **Note**: https://www.tensorflow.org/lite/performance/quantization_spec#specification_summary

![2020-12-26_22-01-31](https://user-images.githubusercontent.com/800129/103157627-f46f5b00-47c5-11eb-9a49-1baa9a27ee47.png)

int8 support is really needed.

**Comment by jackwish** [comment] 2020-12-28 12:44
@kapulkin Thanks for watching this thread. As far as I understand, TensorFlow 2.0 is ***prefer*** `int8` over `uint8` in ***new tool***  rather than _unsupport_ `uint8`. But yes, we should prioritize `int8` support.

**Comment by jackwish** [comment] 2020-12-30 14:39
As with `v0.3.1`, `tflite2onnx` no longer complains about such data type, we may close this issue.

Follow up of these data types:
* [FP16 quantization is not recommended](https://github.com/jackwish/tflite2onnx/issues/30#issuecomment-735403858), but we can fold the FP16 weights into FP32 operator see #35
* INT8 quantization  has been prioritized, see #45

**Comment by jackwish** [comment] 2020-12-30 14:40
Now closing. Please feel free to reopen if there is such issues still. Thank you all for the solid discussion!

**Closed by jackwish** 2020-12-30 14:40 UTC
Labels: Quantization
