### ISSUE TITLE
Potential bug: Reshape(one input, one attr) operator is not supported

### ISSUE THREAD

**Issue by erizmr** [jackwish/tflite2onnx#23] opened 2020-11-09 08:44 UTC
**Describe the bug**
It seems there is another format reshape operator shown below, one input and one attribute, violating assert(op.InputsLength() == 2) in the reshape.py.

![image](https://user-images.githubusercontent.com/33411325/98518529-6831c480-2267-11eb-849c-3df109a8fdc3.png)

**To Reproduce**
model file: [palm_detection.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite)

**Additional context**
To reproduce this bug, there are two operators that have not been supported (prelu, ResizeBilinear) in this model. I have implemented them locally and will try to send a pull request.

**Comment by jackwish** [comment] 2020-11-10 01:28
@erizmr Thank you for moving this issue here.

For the `ResizeBilinear` converting issue you mentioned in #22 , does that blocks you for trying this `Reshape`?

**Comment by erizmr** [comment] 2020-11-10 08:11
I implemented a simple version for `ResizeBilinear`(without handling all the two optional arguments but just filling the first one) and it 'works'(revision is needed) so that I can actually reach the `Reshape`.

**Comment by erizmr** [comment] 2020-11-11 01:32
Hi @jackwish, I finally managed to make the `Reshape` work. Although the `Reshape` with an attribute is quite weird ( I tried `tf.reshape`, `tf.keras.layers.Reshape` but failed to reproduce a `Reshape` block with attribute), it can be naively handled with its option `NewShapeAsNumpy()`, create a vector from it and use it as the second input of `Reshape`.

<img src = https://user-images.githubusercontent.com/33411325/98754030-ab05b080-23bd-11eb-920b-3abc2eb6bff7.png width=500>

**Closed** 2020-11-13 14:22 UTC
Labels: bug

**Comment by Laubeee** [comment] 2020-11-17 10:32
I ran into the same thing trying to convert another mediapipe model: [pose detection](https://github.com/google/mediapipe/tree/master/mediapipe/modules/pose_detection/pose_detection.tflite)

I think there are no PReLU or BesizeBilinear layers there, so the pose detection model could be used to reproduce the Reshape issue separately.

@erizmr could you successfully convert the palm detection with your changes?

**Comment by erizmr** [comment] 2020-11-17 13:29
Hi @Laubeee ,
Yes. I have converted the `palm detection` successfully by adding line 45-line 53 of [reshape.py](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/reshape.py). The lines are commented out because we haven't managed to generate a compact test model for this one input, one attr case.

Also, there is also another issue related to `Reshape` output layout #28. A temporary solution is mentioned in that issue and we are trying to give a solution in production.

The [`prelu`](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/activation.py) and [`ResizeBilinear`](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/resize.py) operators have just been developed very recently, although have not been released to PyPl yet. Feel free to use them from the source if needed.

**Comment by Laubeee** [comment] 2020-11-17 14:08
Thanks, this indeed made the conversion finish successfully. There is an error [on line 51](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/reshape.py#L51) tough:  
`sp.asdtype('int64')` should be  
`sp.astype('int64')`

Will now run the model and see if it gives any sensible output. It looks like there is a high chance this model is also affected by this other issue.

**Comment by erizmr** [comment] 2020-11-21 10:18
Hi @Laubeee ,
The `Reshape` has been updated. And I tested the `pose_detection` model you have mentioned,  the absolute error of the output between the original and transformed model is about `10^{-4}` from my tests, which looks good to me.

**Comment by jackwish** [comment] 2020-11-27 09:26
According to https://github.com/tensorflow/tensorflow/issues/45150#issuecomment-734519579, the one input `Reshape` should be generated by TOCO. We may try the old converter.
